const express = require("express")
const dbConnect = require("./config/dbConnect")
const app = express()
const dotenv= require("dotenv").config()
const cookieParser = require("cookie-parser")
const authRouter = require('./routes/authRoute')
const productRouter = require('./routes/productRoute')
const blogRouter= require("./routes/blogRoute")
const PcatRouter =require("./routes/PcatRoute")
const BcatRouter =require("./routes/BcatRoute")
const brandRouter =require("./routes/brandRoute")
const couponRouter =require("./routes/couponRoute")
const { notFound, errorHandler } = require("./middlewares/errorHandler")
const morgan =require("morgan")
const cors = require('cors')
dbConnect()
const PORT = process.env.PORT||6000
app.use(express.json())
app.use(cors())
app.use(cookieParser())
app.use(morgan("dev"))
app.use("/api/user", authRouter)
app.use("/api/product", productRouter)
app.use("/api/blog", blogRouter)
app.use("/api/category/Pcat", PcatRouter)
app.use("/api/category/Bcat", BcatRouter)
app.use("/api/brand", brandRouter)
app.use("/api/coupon", couponRouter)
app.use(notFound)
app.use(errorHandler)

app.listen(PORT, ()=>{
console.log(`Backend Server Running at PORT ${PORT}`)
})

